# Adding below workaround to resolve the below peer dependency error.
# Error: Jest: Failed to parse the TypeScript config file /home/sid/experiments/next-book/jest.config.ts
# Error: jest-config tried to access ts-node (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.

packageExtensions:
  jest-config@29.7.0:
    dependencies:
      ts-node: ">=9.0.0"

yarnPath: .yarn/releases/yarn-4.4.1.cjs
